# SPDX-License-Identifier: GPL-3.0-or-later
[package]
name = "libredaw-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "ui"

[dependencies]
libredaw-protocol = { path = "../protocol" }
libredaw-plugin-host = { path = "../plugin-host" }
libredaw-engine = { path = "../engine" }
gtk = { package = "gtk4", version = "0.11", features = ["v4_10"] }
adw = { package = "libadwaita", version = "0.9", features = ["v1_5"] }

[[bin]]
name = "libredaw"
path = "src/main.rs"
