#!/usr/bin/env fish
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Generates THIRD_PARTY.md from `cargo metadata` (SPEC.md section 12.1).
# Usage: tools/third-party.fish [output-file]   (default: THIRD_PARTY.md)
#
# Lists every third-party crate in the Linux dependency graph with its
# version and license. Every direct dependency needs a one-line justification
# in `justification` below; the script fails if one is missing.

cd (path resolve (status dirname)/..); or exit 2

set -l out THIRD_PARTY.md
test (count $argv) -ge 1; and set out $argv[1]
set -l target x86_64-unknown-linux-gnu

# One-line justification for each direct dependency.
function justification
    switch $argv[1]
        case cpal
            echo "audio I/O (fixed stack); its `jack` feature pulls in the `jack` crate for the JACK/PipeWire-JACK backend"
        case '*'
            return 1
    end
end

set -l meta (cargo metadata --format-version 1 --locked --filter-platform $target | string collect)
or exit 1

# name<TAB>version<TAB>license for every third-party crate in the resolved graph.
set -l all (echo $meta | jq -r '
    (.packages | map({(.id): .}) | add) as $p
    | [.resolve.nodes[].id | $p[.] | select(.source != null)
       | [.name, .version, (.license // .license_file // "UNKNOWN")]]
    | sort | .[] | @tsv')

# names of third-party crates that a workspace crate depends on directly
set -l direct (echo $meta | jq -r '
    [.packages[] | select(.source == null) | .dependencies[].name] | unique | .[]')

begin
    echo '<!-- SPDX-License-Identifier: GPL-3.0-or-later -->'
    echo '# Third-party software'
    echo
    echo 'Generated by `tools/third-party.fish` from `cargo metadata`. Do not edit by hand;'
    echo 'CI fails if this file is out of date.'
    echo
    echo '## Direct dependencies'
    echo
    echo '| Crate | Version | License | Why |'
    echo '|---|---|---|---|'
    for d in $direct
        set -l why (justification $d)
        or begin
            echo "third-party: direct dependency '$d' has no justification in tools/third-party.fish" >&2
            exit 1
        end
        for line in $all
            set -l f (string split \t -- $line)
            test $f[1] = $d; and echo "| $f[1] | $f[2] | $f[3] | $why |"
        end
    end
    echo
    echo "## All crates in the dependency graph ($target)"
    echo
    echo '| Crate | Version | License |'
    echo '|---|---|---|'
    for line in $all
        set -l f (string split \t -- $line)
        echo "| $f[1] | $f[2] | $f[3] |"
    end
    echo
    echo '## System libraries (hand-maintained)'
    echo
    echo 'Linked dynamically, never bundled. LGPL libraries are only ever linked dynamically.'
    echo
    echo '| Library | License | Used by | Why |'
    echo '|---|---|---|---|'
    echo '| libasound (ALSA) | LGPL-2.1-or-later | engine, through cpal | ALSA audio backend |'
    echo '| libjack (JACK or PipeWire-JACK) | LGPL-2.1-or-later | engine, through the `jack` crate, loaded with dlopen at run time | JACK audio backend |'
    echo '| GTK4 | LGPL-2.1-or-later | ui (planned) | UI toolkit |'
    echo '| libadwaita | LGPL-2.1-or-later | ui (planned) | app shell widgets |'
    echo '| GLib | LGPL-2.1-or-later | ui (planned) | main loop, timers, fd sources |'
end >$out
