#!/usr/bin/env fish
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Generates THIRD_PARTY.md from `cargo metadata` (SPEC.md section 12.1).
# Usage: tools/third-party.fish [output-file]   (default: THIRD_PARTY.md)
#
# Lists every third-party crate in the Linux dependency graph with its
# version and license. Every direct dependency needs a one-line justification
# in `justification` below; the script fails if one is missing.

cd (path resolve (status dirname)/..); or exit 2

set -l out THIRD_PARTY.md
test (count $argv) -ge 1; and set out $argv[1]
set -l target x86_64-unknown-linux-gnu

# One-line justification for each direct dependency.
function justification
    switch $argv[1]
        case cpal
            echo "audio I/O (fixed stack); its `pipewire` feature adds the native PipeWire host (pipewire, libspa, and bindgen at build time), its `realtime-dbus` feature promotes the PipeWire callback thread to SCHED_RR through rtkit (audio_thread_priority, dbus), and its `jack` feature the JACK backend"
        case clap-sys
            echo "raw CLAP C ABI bindings for plugin hosting, SPEC 9.1 (plugin-host)"
        case libloading
            echo "dlopen of .clap plugin files (plugin-host)"
        case dbus
            echo "Flatpak realtime portal call that gives the audio thread real-time priority (engine); already pulled in by cpal realtime-dbus"
        case libc
            echo "RLIMIT_RTTIME and thread id for the realtime portal (engine); already pulled in by cpal"
        case tract-onnx
            echo "pure-Rust ONNX runtime that runs the Basic Pitch hum-to-notes model on the CPU, SPEC 21.3 (transcribe); MIT OR Apache-2.0"
        case symphonia
            echo "decode FLAC, Ogg Vorbis (also inside FL Studio WAV files), MP3 and PCM WAV samples, SPEC 15.3 (audiofile); MPL-2.0; features wav, pcm, flac, vorbis, ogg, mp3 only"
        case wavicle
            echo "pure-Rust lossless WavPack decoder for FL Studio sample packs, SPEC 15.3 (audiofile); MIT OR Apache-2.0, no unsafe, no dependencies"
        case glib
            echo "timer, fd, and X11 event sources on the GTK main context for plugins (plugin-host; also ui through gtk4)"
        case x11rb
            echo "X11 top-level window for plugin GUIs that need a parent, SPEC 9.2 (plugin-host)"
        case rtrb
            echo "wait-free SPSC rings for the state, retire, command, plugin-event and event rings, SPEC 4.2 and 4.4 (engine)"
        case gtk4
            echo "GTK4 bindings, the app toolkit (ui); feature v4_10"
        case libadwaita
            echo "AdwApplicationWindow, toasts, dialogs (ui); feature v1_5"
        case serde
            echo "derive (de)serialization for the project file and the control API (protocol); typed MCP tool arguments (mcp)"
        case toml
            echo "parse the project file, SPEC 7.2 (protocol); saving uses our own emitter"
        case serde_json
            echo "JSON for the control API used by scripts and agents (protocol tests now; ui, script, mcp later)"
        case '*'
            return 1
    end
end

set -l meta (cargo metadata --format-version 1 --locked --filter-platform $target | string collect)
or exit 1

# name<TAB>version<TAB>license for every third-party crate in the resolved graph.
set -l all (echo $meta | jq -r '
    (.packages | map({(.id): .}) | add) as $p
    | [.resolve.nodes[].id | $p[.] | select(.source != null)
       | [.name, .version, (.license // .license_file // "UNKNOWN")]]
    | sort | .[] | @tsv')

# names of third-party crates that a workspace crate depends on directly
set -l direct (echo $meta | jq -r '
    [.packages[] | select(.source == null) | .dependencies[] | select(.path == null) | .name] | unique | .[]')

begin
    echo '<!-- SPDX-License-Identifier: GPL-3.0-or-later -->'
    echo '# Third-party software'
    echo
    echo 'Generated by `tools/third-party.fish` from `cargo metadata`. Do not edit by hand;'
    echo 'CI fails if this file is out of date.'
    echo
    echo '## Direct dependencies'
    echo
    echo '| Crate | Version | License | Why |'
    echo '|---|---|---|---|'
    for d in $direct
        set -l why (justification $d)
        or begin
            echo "third-party: direct dependency '$d' has no justification in tools/third-party.fish" >&2
            exit 1
        end
        for line in $all
            set -l f (string split \t -- $line)
            test $f[1] = $d; and echo "| $f[1] | $f[2] | $f[3] | $why |"
        end
    end
    echo
    echo "## All crates in the dependency graph ($target)"
    echo
    echo '| Crate | Version | License |'
    echo '|---|---|---|'
    for line in $all
        set -l f (string split \t -- $line)
        echo "| $f[1] | $f[2] | $f[3] |"
    end
    echo
    echo '## System libraries (hand-maintained)'
    echo
    echo 'Linked dynamically, never bundled. LGPL libraries are only ever linked dynamically.'
    echo
    echo '| Library | License | Used by | Why |'
    echo '|---|---|---|---|'
    echo '| libasound (ALSA) | LGPL-2.1-or-later | engine, through cpal | ALSA audio backend |'
    echo '| libpipewire-0.3 (PipeWire) | MIT | engine, through cpal'\''s `pipewire` feature (pipewire-sys links it) | native PipeWire audio backend |'
    echo '| libjack (JACK or PipeWire-JACK) | LGPL-2.1-or-later | engine, through the `jack` crate, loaded with dlopen at run time | JACK audio backend |'
    echo '| libclang (build time only) | Apache-2.0 WITH LLVM-exception | bindgen, while building pipewire-sys | generates the libpipewire bindings; not linked into our binaries |'
    echo '| libdbus-1 | AFL-2.1 OR GPL-2.0-or-later (used under GPL-2.0-or-later) | engine, through cpal'\''s `realtime-dbus` feature (libdbus-sys) | asks rtkit to make the audio thread real-time |'
    echo '| GTK4 | LGPL-2.1-or-later | ui | UI toolkit |'
    echo '| libadwaita | LGPL-2.1-or-later | ui | app shell widgets |'
    echo '| GLib | LGPL-2.1-or-later | ui, plugin-host | main loop, timers, fd sources |'
end >$out
